server:
  port: 9999
spring:
  application:
    name: example
  datasource:
    password: a
    username: a
    url: "jdbc:h2:~/squash-test.db"
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: container
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
server:
  port: ${SERVER_PORT}